# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170724_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_type',
            field=models.CharField(blank=True, choices=[('SF', 'Single Family'), ('TH', 'Townhome'), ('CN', 'Condominium'), ('OT', 'Other Options')], max_length=2),
        ),
    ]
