# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170804_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interested_cities',
        ),
        migrations.AddField(
            model_name='city',
            name='interested_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to=settings.AUTH_USER_MODEL),
        ),
    ]
