# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 07:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170805_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2777181947'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='purchase_step',
            field=models.CharField(choices=[('DAP', 'Decide and Prepare'), ('EAO', 'Evaluate and Offer'), ('HOB', 'Home owner benefits')], default='DAP', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_age',
            field=models.CharField(choices=[('HD', 'High Density'), ('MD', 'Medium Density'), ('LD', 'Low Density'), ('AW', 'Anywhere')], default='AW', max_length=2),
        ),
    ]
