from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(
        r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'
    ),
    url(
        r'^faq$',
        TemplateView.as_view(template_name='mainapp/faq.html'),
        name='faq'
    ),
    url(
        r'^privacy$',
        TemplateView.as_view(template_name='mainapp/privacy.html'),
        name='privacy'
    ),
    url(
        r'^terms$',
        TemplateView.as_view(template_name='mainapp/terms.html'),
        name='terms'
    ),
    url(
        r'^prepare$',
        TemplateView.as_view(template_name='mainapp/prepare.html'),
        name='prepare'
    ),
    url(
        r'^purchase$',
        TemplateView.as_view(template_name='mainapp/purchase.html'),
        name='purchase'
    ),
    url(
        r'^own$',
        TemplateView.as_view(template_name='mainapp/own.html'),
        name='own'
    ),
    url(
        r'^onboarding$',
        TemplateView.as_view(template_name='mainapp/onboarding.html'),
        name='onboarding'
    ),
    url(
        r'^onboarding/prepare/profile$',
        TemplateView.as_view(template_name='mainapp/onboarding_prepare/profile.html'),
        name='prepare-profile'
    ),
    url(
        r'^onboarding/prepare/first-time$',
        TemplateView.as_view(template_name='mainapp/onboarding_prepare/is_first_home.html'),
        name='prepare-firsttime'
    ),
    url(
        r'^onboarding/prepare/home-type$',
        TemplateView.as_view(template_name='mainapp/onboarding_prepare/type_home.html'),
        name='prepare-hometype'
    ),
    url(
        r'^onboarding/prepare/max-budget',
        TemplateView.as_view(template_name='mainapp/onboarding_prepare/max_budget.html'),
        name='prepare-maxbudget'
    ),
    url(
        r'^onboarding/prepare/rent',
        TemplateView.as_view(template_name='mainapp/onboarding_prepare/rent.html'),
        name='prepare-rent'
    ),
    url(
        r'^onboarding/prepare/timeline',
        TemplateView.as_view(template_name='mainapp/onboarding_prepare/timeline.html'),
        name='prepare-timeline'
    ),
    url(
        r'^signup',
        TemplateView.as_view(template_name='pages/sign-up.html'),
        name='signup'
    ),

]
