branch-defaults:
  dev:
    environment: realpal-dev
environment-defaults:
  realpal-dev:
    branch: null
    repository: null
global:
  application_name: realpal
  default_ec2_keyname: real-dev
  default_platform: Python 3.4
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
