# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house_age',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'New Construction'), (1, 'One to Fifteen'), (2, 'Fifteen to thirty'), (3, 'Over thirty')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_cond',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Updated'), (1, 'Slightly dated'), (2, 'Fixer Upper')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Single Family'), (1, 'Townhome'), (2, 'Condominium'), (3, 'New Construction'), (4, 'Other Options'), (5, 'Flexible')], null=True),
        ),
    ]
