# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170827_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Single'), (1, 'Married with No Kids'), (2, 'Married with No School Kids'), (3, 'Married with School Kids'), (4, 'Investor')], default=0, null=True),
        ),
    ]
