# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170725_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firsthome',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='how_soon',
            field=models.CharField(choices=[('3', '0-3 Months'), ('6', '3-6 Months'), ('12', '6-12 Months'), ('12+', '12+ Months'), ('SK', 'Skip')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_type',
            field=models.CharField(blank=True, choices=[('SF', 'Single Family'), ('TH', 'Townhome'), ('CN', 'Condominium'), ('NC', 'New Construction'), ('OT', 'Other Options')], max_length=2),
        ),
    ]
