# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170828_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='how_soon',
            field=models.SmallIntegerField(blank=True, choices=[(0, '0-3 Months'), (1, '3-6 Months'), (2, '6-12 Months'), (3, '12+ Months'), (4, 'Skip')], null=True),
        ),
    ]
