# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170818_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'Agent'), (1, 'Client')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.SmallIntegerField(choices=[(0, '780+'), (1, '740-779'), (2, '700-739'), (3, '650-699'), (4, '600-649'), (5, '<599')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_age',
            field=models.SmallIntegerField(choices=[(0, 'New Construction'), (1, 'One to Fifteen'), (2, 'Fifteen to thirty'), (3, 'Over thirty')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_cond',
            field=models.SmallIntegerField(choices=[(0, 'Updated'), (1, 'Slightly dated'), (2, 'Fixer Upper')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='house_type',
            field=models.SmallIntegerField(choices=[(0, 'Single Family'), (1, 'Townhome'), (2, 'Condominium'), (3, 'New Construction'), (4, 'Other Options'), (5, 'Flexible')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='how_soon',
            field=models.SmallIntegerField(choices=[(0, '0-3 Months'), (1, '3-6 Months'), (2, '6-12 Months'), (3, '12+ Months'), (4, 'Skip')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.SmallIntegerField(choices=[(0, 'English'), (1, 'Spanish'), (2, 'Mandarin/Cantonese'), (3, 'Hindi'), (4, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchase_step',
            field=models.SmallIntegerField(choices=[(0, 'Decide and Prepare'), (1, 'Evaluate and Offer'), (2, 'Home owner benefits')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Single'), (1, 'Married with No Kids'), (2, 'Married with No School Kids'), (3, 'Married with School Kids'), (4, 'Investor')], default=0),
        ),
    ]
