# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170818_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='interested_users',
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realpal.apps.users.City'),
        ),
    ]
