# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170906_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2777181947'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
