# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170906_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firsthome',
            field=models.BooleanField(),
        ),
    ]
