# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170906_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_city',
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_city',
            field=models.ManyToManyField(to='users.City'),
        ),
    ]
