# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170906_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firsthome',
            field=models.BooleanField(default=False),
        ),
    ]
