# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20170906_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_mortgage',
            field=models.BooleanField(default=False),
        ),
    ]
