# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170913_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='purchase_step',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Decide and Prepare'), (1, 'Evaluate and Offer'), (2, 'House owning')], default=0, null=True),
        ),
    ]
