# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170913_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firsthome',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_agent',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_mortgage',
            field=models.NullBooleanField(default=False),
        ),
    ]
