# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20170825_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to=settings.AUTH_USER_MODEL),
        ),
    ]
